import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Logo from "../Assets/Images/loocafe-logo.png";
import SearchIcon from "@mui/icons-material/Search";
import LiveData from "../Components/liveData";
import Map from "../Components/Map";
import { Button, TextField } from "@mui/material";

export default function Home() {
  return (
    <div className="text-center w-screen">
      <Head>
        <title>Search cafes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-blue-400 h-24">
        <div className="mx-10">
          <Link href="https://loocafe.com/">
            <Image
              className="hover:cursor-pointer"
              src={Logo}
              height={95}
              width={100}
            />
          </Link>
        </div>
      </header>
      <main>
        <section className="flex justify-center space-x-5">
          <TextField
            variant="outlined"
            label="Enter the Area"
            className="w-96 my-5 shadow-lg"
          />
          <Button
            className="h-12 w-20 mt-6 bg-blue-400 shadow-lg"
            variant="contained"
            size="medium"
          >
            <SearchIcon />
          </Button>
        </section>
        <section className="flex justify-center">
          <div className="h-96 w-10/12">
            <Map lat={59.955413} lng={30.337844} text="My Marker" />
          </div>
        </section>
        <div className="mt-5 flex justify-center w-screen mb-5">
          <LiveData />
        </div>
      </main>
      <footer className="bg-blue-400 h-24"></footer>
    </div>
  );
}
